### ISSUE TITLE
Crash Loop on Windows

### ISSUE THREAD

**Issue by DavidA122** [LanikSJ/slack-dark-mode#204]
**Describe the bug**
When installing the dark theme using the instructions provided (cd into directory, run `.\slack-dark-mode.ps1`), Slack enters a crash/reboot loop when loading the sidebar/selected channel.

**To Reproduce**
1\. Install via Windows PowerShell
2\. Open Slack
3\. Observe reboot

Running `.\slack-dark-mode.ps1 -LightMode` does not resolve the issue

**Expected behavior**
Dark Mode to function as previous

**Desktop (please complete the following information):**

-   OS: Windows 10 Pro, version 1903
-   Slack Version: v4.0.2

**Additional context**
The theme was working as expected yesterday (29th August), but no releases from Slack this morning.

Not familiar with what logs Slack produces, so if you need any, let me know.

EDIT: Workaround/fix available here: https://github.com/LanikSJ/slack-dark-mode/issues/204#issuecomment-528541047

**Comment by tsqn** [comment]
Same problem, reinstalling the Slack doesn't help.

**Comment by KTsarlz** [comment]
Same. I'm having this issue. Reinstalling doesn't stop it.

**Comment by LanikSJ** [comment]
@krazyito65 any ideas? I don't have Windows so I can't really reproduce this.

**Comment by KTsarlz** [comment]
In my case, I just went to work and loaded slack. To my surprise, it doesnt load anymore. When I open slack, it'll show the loading circle and then will crash. It'll do that endlessly, I tried to uninstall and then install. Doesn't work either.. Not sure what changed

**Comment by npetter** [comment]
For anyone struggling with this. To make it work again, you need to do the following:

1. Uninstall Slack
2. Delete C:\Users\<user>\AppData\Roaming\Slack folder
3. Install Slack

**Comment by krazyito65** [comment]
Sorry.. Classic WoW has eaten up a lot of my time....

I haven't seen this issue at all on my windows version, so hopefully @npetter suggestion will work.

**Comment by DavidA122** [comment]
It's worth clarifying that @npetter's suggestion only reverts Slack to a functioning (light theme) state, with no toggle to dark mode.

I've replicated this issue on a new machine (as I've moved to a laptop at work) and am still experiencing the same issue. As in @KTsarlz's case, I also arrived at work to find the theme not functioning correctly, after it working correctly at 5pm the previous day.

**Comment by krazyito65** [comment]
I think it was implied that you re-run the script after you uninstall since, yes obviously, our changes would be removed.

**Comment by krazyito65** [comment]
And now the issue is happening to me.  Going to try these suggestions.

**Comment by krazyito65** [comment]
Steps I performed:

1. uninstall
2. delete `%appdata%\Slack`
3. install slack
4. sign-in
5. `git pull` dark mode script
6. run `.\slack-dark-mode.ps1`

works fine for me now.

**Comment by DavidA122** [comment]
Unfortunately the above steps aren't working for me.

On first load following uninstall, reinstall, and re-run of script, the "Loading" screen is first in dark theme, then light, then dark, and shortly after, closes.

On each subsequent load, the loading screen is white and closes within 3 seconds.

This was with both a fresh copy of Slack and the dark mode script.

**Comment by krazyito65** [comment]
Did you download a fresh installer (4.02) from the slack website?

**Comment by DavidA122** [comment]
Yep, fresh installer.

In %AppData%\Local\slack\, I have only app-4.0.2 and packages as directories

**Comment by krazyito65** [comment]
And when you uninstall slack, is the `%localappdata%\slack` folder gone?

**Comment by DavidA122** [comment]
Not entirely, "Update.exe" and ".dead" remains, but "Update.exe" has a modified time of when I ran the new installer (4.02) downloaded 1 minute prior.

Uninstall process is removing the program via the control panel (Search "Slack" in Windows menu -> right-click Slack -> "Uninstall" -> Select "Slack" -> "Uninstall")

**Comment by krazyito65** [comment]
open power shell
`node --version`
`npm --version`

**Comment by DavidA122** [comment]
PS C:\Windows\system32> node --version
v10.16.3
PS C:\Windows\system32> npm --version
6.9.0

**Comment by krazyito65** [comment]
try updating to 12.7 and 6.10 at least (thats what i have)

**Comment by DavidA122** [comment]
Some progress! Slack did eventually stay open with the dark mode, but this was following a number of restarts. Upon closing Slack, and reopening, I've not yet had Slack stay active after 10+ crashes/restarts (by Slack itself).

Process followed:

- Uninstall Slack from Windows
- Delete %AppData%/Local/slack and %AppData%/Roaming/Slack
- Update node.js to v12.9.1 (latest version) and npm to v6.10.2
- Reinstall Slack
- Sign in
- Run script
- Open Slack

**Comment by krazyito65** [comment]
its pretty difficult for me to troubleshoot since its not happening to me..

Do you open Slack at least once before you run the script?  Do you allow the script to force kill slack?

**Comment by krazyito65** [comment]
or did i misunderstand and now it works?

**Comment by DavidA122** [comment]
I do, as I have to open Slack to sign in first. Running the script without signing in gives errors due to non-existent files.

I've tried both methods. Allowing the script to force-close Slack seems to be less successful, as first closing Slack, then running the script allows Slack to open once, but this isn't consistent. However, what is consistent is that if Slack is closed, it will not reopen successfully.

**Comment by DavidA122** [comment]
To further complicate the issue, after an "unsuccessful" install where Slack continuously restarted, it did eventually settle on the dark theme and load my channels successfully.

After quitting and reopening Slack after this occurrence, Slack does load correctly again (after approx 5-7 minutes? Rough time.)

**Comment by krazyito65** [comment]
i mean, at least it works now?  not really sure what else we can do

**Comment by DavidA122** [comment]
Well, I wouldn't say it works in that it takes 10 minutes to open Slack in the current configuration. Have you tried uninstalling and reapplying the dark mode? As didn't this trigger the issue on your environment?

**Comment by krazyito65** [comment]
yea i uninstalled 3 times and re did my original steps, all works fine.

**Comment by krazyito65** [comment]
@KTsarlz could you try on your end what we've tried?

**Comment by KTsarlz** [comment]
I just to work, will try the suggestion here and will update you guys with my findings

**Comment by KTsarlz** [comment]
So my results are.. 

After testing is that is still not working. My nodejs and npm is also updated, cleaned the files in Appdata reinstalled slack and after signing in I am still presented with the reloading circle endlessly. Should I just let it ran?

**Comment by KTsarlz** [comment]
I also tried running the script and letting it close slack and closing slack and then ran the script. I'm still presented with the connecting to slack white page and then slack opens with dark theme for about 1-2 secs and then do it all over again

**Comment by krazyito65** [comment]
not sure if it makes a difference, but im on Windows 10 enterprise, 17134

**Comment by KTsarlz** [comment]
Hmmn. Slack has been going on for more than 10 minutes now and it's still doing it's things..

On this machine I am on Windows 10 Pro

**Comment by krazyito65** [comment]
@nlowe any insight?

**Comment by nlowe** [comment]
Hmm, I didn't notice this yesterday on my machine at home, will take a look when I get off work today. One of my co-workers is experiencing this with a specific workspace.

It looks like everyone on this thread is using the AppData / User-specific installer and not the machine-wide MSI right?

**Comment by nlowe** [comment]
@DavidA122 Can you make a separate issue about the missing files errors if you try to run the script without logging in first? The script and/or README should be more clear on the order things need to happen.

**Comment by krazyito65** [comment]
yea not the MSI, we're just using what we get directly from the slack website.

**Comment by KTsarlz** [comment]
Yeah, I use the one from the official site

**Comment by nlowe** [comment]
This is still working fine for me on 4.0.1 and 4.0.2 via the MSI. Let me spin up a VM and install the user-profile based version and see if I can repro this.

**Comment by nlowe** [comment]
Hmm, I'm unable to reproduce this with the user-profile (appdata) based installer on a fresh machine. For those affected:

* Remove all workspaces and re-add them one by one to see if it's a specific workspace that's causing the issue
* Run this and paste the output in a code block:
    ```powershell
    $SlackBase = Join-Path -Path $env:LOCALAPPDATA -ChildPath slack
    
    if (-not (Test-Path -Path $SlackBase)) {
        Write-Output "Checking for MSI-based installations"
        $latestPath = Join-Path -Path $env:ProgramFiles -ChildPath "Slack"
        if (-not (Test-Path -Path $latestPath)) {
            throw "It doesn't look like slack is installed"
        }
    
        Write-Output "Found Slack MSI Install"
    } else {
        $latestPath = Get-ChildItem -Path $SlackBase -Directory -Filter "app*" | Sort-Object -Descending | Select-Object -First 1 -ExpandProperty FullName
        Write-Output "Found Slack $($latestPath) in AppData"
    }
    Get-Content $latestPath\resources\app.asar.unpacked\dist\ssb-interop.bundle.js | Select -Skip 1
    ```

That powershell block will show me what got appended to your interop file, perhaps something got corrupted. A working one should look something like this:

```javascript
Found Slack C:\Users\Nathan\AppData\Local\slack\app-4.0.2 in AppData
//# sourceMappingURL=ssb-interop.bundle.js.map

// BEGIN CUSTOM THEME

document.addEventListener('DOMContentLoaded', function() {
  const fs = require('fs');
  const filePath = "C:/Users/Nathan/AppData/Local/slack/app-4.0.2/resources/custom_theme.css";
  const IS_DARK_KEY = "isDark";

  fs.readFile(filePath, {
    encoding: 'utf-8'
  }, function(err, css) {
    if (!err) {
      const styleEl = document.createElement("style");
      const head = document.querySelector("head");
      styleEl.innerHTML = css;

      if (localStorage.getItem(IS_DARK_KEY) === null) {
        localStorage.setItem(IS_DARK_KEY, true);
        window.location.reload(true);
      }

      if (JSON.parse(localStorage.getItem(IS_DARK_KEY))) {
        head.append(styleEl);
      }

      document.addEventListener("keydown", event => {
        if (event.ctrlKey && event.keyCode === 76) {
          const isDark = JSON.parse(localStorage.getItem(IS_DARK_KEY));
          isDark ? head.removeChild(styleEl) : head.append(styleEl);
          localStorage.setItem(IS_DARK_KEY, !isDark);
        }
      });
    }
  });
});

// END CUSTOM THEME
```

**Comment by krazyito65** [comment]
the issue is happening on my home computer running windows 10 pro 17763


Here is the output
```js
Locating Slack
Found Slack  in AppData
Stopping Slack
Updating Theme File
Fetching Theme from https://raw.githubusercontent.com/LanikSJ/slack-dark-mode/master/dark-theme.css
Unpacking asar archive
npx: installed 21 in 7.45s
Adding Hook
Packing asar archive
npx: installed 21 in 2.224s
Adding workaround to ensure theme boots
PS C:\Users\LeonSolis\Documents\git-repos\slack-dark-mode> .\test.ps1
Found Slack C:\Users\LeonSolis\AppData\Local\slack\app-4.0.2 in AppData
//# sourceMappingURL=ssb-interop.bundle.js.map

// BEGIN CUSTOM THEME

document.addEventListener('DOMContentLoaded', function() {
  const fs = require('fs');
  const filePath = "C:/Users/LeonSolis/AppData/Local/slack/app-4.0.2/resources/custom_theme.css";
  const IS_DARK_KEY = "isDark";

  fs.readFile(filePath, {
    encoding: 'utf-8'
  }, function(err, css) {
    if (!err) {
      const styleEl = document.createElement("style");
      const head = document.querySelector("head");
      styleEl.innerHTML = css;

      if (localStorage.getItem(IS_DARK_KEY) === null) {
        localStorage.setItem(IS_DARK_KEY, true);
        window.location.reload(true);
      }

      if (JSON.parse(localStorage.getItem(IS_DARK_KEY))) {
        head.append(styleEl);
      }

      document.addEventListener("keydown", event => {
        if (event.ctrlKey && event.keyCode === 76) {
          const isDark = JSON.parse(localStorage.getItem(IS_DARK_KEY));
          isDark ? head.removeChild(styleEl) : head.append(styleEl);
          localStorage.setItem(IS_DARK_KEY, !isDark);
        }
      });
    }
  });
});

// END CUSTOM THEME
```

**Comment by nlowe** [comment]
@krazyito65 That looks fine to me. Do you have any other `app-*` folders in `C:/Users/LeonSolis/AppData/Local/slack`?

**Comment by krazyito65** [comment]
by the way.... i had to do some work to get this to even work on my home computer because i had to go through the registry and update my User folder to remove the space since npx was having issues with the path....

**Comment by krazyito65** [comment]
> @krazyito65 That looks fine to me. Do you have any other `app-*` folders in `C:/Users/LeonSolis/AppData/Local/slack`?

no only 4.0.2.  I actually never had slack installed as an app on this PC.

**Comment by nlowe** [comment]
Interesting. Definitely make a separate issue for that, we should definitely handle that use case gracefully. What's the output of:

```powershell
Get-Content (Join-Path -Path $env:APPDATA -ChildPath "Slack" | Join-Path -ChildPath "local-settings.json")
```

**Comment by krazyito65** [comment]
```ps
PS C:\Users\LeonSolis> Get-Content (Join-Path -Path $env:APPDATA -ChildPath "Slack" | Join-Path -ChildPath "local-settings.json")
{"lastElectronVersionLaunched":"4.2.8","bootSonic":"never","lastKnownLocale":"en-US","useHwAcceleration":true,"spellCheckerVersion":"V1"}
```

**Comment by nlowe** [comment]
Everything looks fine on the surface. Can you upload your `app.asar` (not the unpacked folder) to google drive or something? I want to compare it to one of my working installs.

**Comment by krazyito65** [comment]
https://drive.google.com/file/d/1L6rng5NhEjGMsBxJkGd0-R84LYncCUbZ/view?usp=sharing

**Comment by nlowe** [comment]
It appears the AppData install and MSI Install archives are different but my working archive from an appdata folder is exactly the same as yours with the exception of the theme path. What Locale / Language is your machine set to?

**Comment by krazyito65** [comment]
uhhhh.... English NA?

**Comment by nlowe** [comment]
Yeah I'm out of ideas for things to look at. The only thing I can recommend is uninstalling slack, nuking `$env:APPDATA\slack` and `$env:LOCALAPPDATA\slack`, re-install, and try again. I'm not sure of ways to get logs out of the client and it doesn't look like there's a way to enable dev tools to see JS errors.

**Comment by nlowe** [comment]
Actually, if you still have `$env:APPDATA\Slack`, can you throw all of the `.log` files in `$env:APPDATA\Slack\logs` in a gist? Maybe there'll be something helpful in there.

**Comment by krazyito65** [comment]
that points to `%appdata%/Slack` right?

**Comment by nlowe** [comment]
Correct, sorry, `$env:APPDATA` is the powershell syntax, `%appdata` is the command-prompt syntax.

**Comment by krazyito65** [comment]
Yea, I'm just use to putting it into the file explorer like that.

https://drive.google.com/file/d/1dzQdtkqHOblvqXUkOdO5fAo0LiFTAim5/view

**Comment by krazyito65** [comment]
at worst, might have to wait for a new slack update to see if it helps =/.  Its a really odd issue and not sure at all why the simple js would cause it.

**Comment by nlowe** [comment]
Nothing in those logs jumps out at me `¯\_(ツ)_/¯`

To clarify: You can't start slack at *all*, you get stuck at:
![image](https://user-images.githubusercontent.com/794251/64303116-ac834f80-cf54-11e9-9093-74f8c33abdfd.png)

**Comment by krazyito65** [comment]
yes it loops, it will load, i see the dark mode applied, and then it crashes and tries to load again.

**Comment by nlowe** [comment]
Oh interesting. So it actually goes through and loads but crashes ***after*** it opens. Anything funky in Event Viewer's application log?

**Comment by krazyito65** [comment]
how do i check that

**Comment by nlowe** [comment]
1. Start > Search for `eventvwr` > Click on `Event Viewer`
2. In the right hand side bar, expand `Windows Logs`
3. Click `Application`

We're looking for errors or warnings, particularly those about `slack.exe` or things that contain `slack / electron` in the event details in the lower-middle of the screen.

**Comment by krazyito65** [comment]
can't really find anything but its possible im still not sure what im looking for

**Comment by krazyito65** [comment]
trying to do a find, its still going, but its been running for a bit now.

**Comment by nlowe** [comment]
Unfortunately there's not much else I'm able to do remotely, I guess we'll have to wait for an update to see if something changes, more info from others with this issue, or until my install breaks. Sorry!

**Comment by jayhill** [comment]
These DCOM errors appear in the Windows system logs in conjunction with each crash:
```
The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{2593F8B9-4EAF-457C-B68A-50F6B8EA6B54}
 and APPID 
{15C20B67-12E7-4BB6-92BB-7AFF07997402}
 to the user COMPUTER\User SID (S-1-5-21-2304391736-3849423409-1238163763-1001) from address LocalHost (Using LRPC) running in the application container Unavailable SID (Unavailable). This security permission can be modified using the Component Services administrative tool.
```
_where `COMPUTER` is the machine name and `User` is the username_

That APPID is for the RuntimeBroker, and I can't find anything about that CLSID.
There are various threads about these errors around, but I didn't find anything to help me resolve this.

**Comment by krazyito65** [comment]
What windows build number is everyone using when seeing their issues?  

- Working:
  - Windows 10 enterprise, 17134 (krazyito)
- Not working:
  - windows 10 pro 17763 (krazyito)

Maybe we can see a pattern.

**Comment by krazyito65** [comment]
Interesting.... my enterprise is starting to do it now when I added my 2nd workspace... Actually seems like a workspace issue.

**Comment by krazyito65** [comment]
To be clear, I have 2 workspaces, one paid and one free.  When my enterprise was working, I was only using the paid workspace, when i added the free, it started loop crashing

I cleared the `%appdata%\Slack` folder and only free workspace, it rebooted once, but now it works fine.

I added the paid one, now everything works fine still..

I switch to the free workspace.... and still works...  Going to try again, and add paid first, then free.

**Comment by nlowe** [comment]
That sounds very similar to what my co-worker was seeing. I only have one workspace so there's a good chance that's why I'm not seeing this issue. I wonder why it only affects windows?

**Comment by krazyito65** [comment]
Now this time when i do Paid first, free 2nd, it did 1 loop crash, but now works fine.  Earlier today it was loop crashing constantly. 

Not sure if the paid status of the workspace matters or not, but would love to hear other people here test adding workspaces to see when it happens.

**Comment by KTsarlz** [comment]
I only have 1 workspace ever since I use slack at work. It's paid I think. I can't even add another workspace once logged in since it crashes endlessly

**Comment by krazyito65** [comment]
> It's paid I think. 
can you confirm for sure if its paid or not?  I'm having doubts its causing the problem, but I want to have as many compare points as possible.

**Comment by krazyito65** [comment]
its so weird, its working completely fine with both workspaces now on my enterprise machine.

**Comment by krazyito65** [comment]
Can someone try deleting the folder in roaming after you see the issue? (instead of uninstalling)

**Comment by KTsarlz** [comment]
So I tried to do it again. Uninstalled slack, removed files in Local and Roaming in %appdata%, installed slack and then signed it to my workspace. Well mine does not say on which plan but it says part of the Oracle organization. Deleted the local repo and cloned it again ran the script. It's still doing the loading and crashing thingy just as @krazyito65 said

**Comment by krazyito65** [comment]
Can you kill slack, delete the roaming folder only, then sign in again?

**Comment by jayhill** [comment]
☝️ This worked for me.
The first time I signed into my workspace after doing it, the dark theme was not applied.
Every time since, it has come up dark, and I have now added 6 workspaces.
I have restarted Slack ~10 times and have not had any restart looping so far.

**Comment by jayhill** [comment]
I still get a DCOM error in the system logs when Slack starts, but I guess that was just a red herring wrt this issue.

**Comment by KTsarlz** [comment]
@krazyito65 That worked for me! Finally. Thanks a lot.

**Comment by krazyito65** [comment]
for some reason the issue came up on first boot after applying the dark theme..

**Comment by krazyito65** [comment]
As a TLDR for this post for whoever comes in:

If you're getting the boot loop error where it continually crashes and tries to reboot, do the following:

1. Kill Slack process completely.  You should be able to right click from the task bar on the bottom right and hit 'quit slack'
2. Open a folder and go to `%appdata%` and delete the folder called `Slack` (capital S, NOT LOWER CASE)
3. Start up Slack and sign in to your workspaces.

I have a feeling this WILL happen again when you get a new slack update (assuming the update does not fix it).  Which means you will need to do this again.

PLEASE NOTE, UNINSTALLING SLACK COMPLETELY WILL CAUSE THIS ERROR TO HAPPEN ON FIRST BOOT. Just delete your Slack Roaming folder and it should be good to go.

**Comment by krazyito65** [comment]
please upvote this for future readers ^

**Comment by krazyito65** [comment]
I'm going to do some more testing knowing this to see if i can make it consistently fail and then work, and then maybe we can do something in the script on a normal install to 'workaround' it.

**Comment by krazyito65** [comment]
weird, it wasn't working properly, but now all of a sudden it is... had the same issue where the dark theme was not applied, but when i swapped workspaces it worked everywhere.

Its not an ideal solution, but at least it works /shrug

**Comment by DavidA122** [comment]
Checked out of this thread for a day or two, but I've come back and my Slack is now working perfectly with the dark mode as suddenly as the issue started... I'm hesitant to touch things, but seems like deleting the "Slack" folder within AppData seems to be a resolution here.

I'll open up the bug report RE running the script without signing in now

**Comment by kakins** [comment]
> As a TLDR for this post for whoever comes in:
> 
> If you're getting the boot loop error where it continually crashes and tries to reboot, do the following:
> 
> 1. Kill Slack process completely.  You should be able to right click from the task bar on the bottom right and hit 'quit slack'
> 2. Open a folder and go to `%appdata%` and delete the folder called `Slack` (capital S, NOT LOWER CASE)
> 3. Start up Slack and sign in to your workspaces.
> 
> I have a feeling this WILL happen again when you get a new slack update (assuming the update does not fix it). Which means you will need to do this again.
> 
> PLEASE NOTE, UNINSTALLING SLACK COMPLETELY WILL CAUSE THIS ERROR TO HAPPEN ON FIRST BOOT. Just delete your Slack Roaming folder and it should be good to go.

I can confirm that this worked for me also.  For clarity, on Windows I had to delete the "Slack" folder in %appdata%/Roaming.

**Comment by krazyito65** [comment]
`%appdata%` defaults to Roaming, while %localappdata% goes to the Local folder, which is why I worded it as such.

**Comment by krazyito65** [comment]
@LanikSJ seems we have a fix then... but its more like a work around until new versions of slack stop causing it.  Not sure if you want to close this or what you want to do with it.

**Comment by LanikSJ** [comment]
I'm okay closing this for now and pinning it so folks can find this if they're having trouble.

**Comment by nlowe** [comment]
Interesting, just started happening to me. I wonder if slack is a/b testing something?

**Comment by LanikSJ** [comment]
Or they are doing a phased rollout.

**Comment by nlowe** [comment]
I found a fix. It is indeed a phased rollout.

**Comment by nlowe** [comment]
A fix for this is now in `master`. Can everyone on this issue please pull the latest `master` and verify it's fixed? If you're crash-looping currently the script should fix it without any additional flags. If you're installing for the first time slack may restart once but should not crash-loop.

**Comment by KTsarlz** [comment]
I can’t test currently since it’s the weekend and I am not near my work or personal computer. I’ll let the others chime in and verify the fix. And will do my own testing on tomorrow

**Comment by krazyito65** [comment]
why is windows so dumb... This is what I did:

Open slack with no changes from the other day, loop-crashing.
update my local git repo and run the script with no flags, still get look=crash
run script with `-ForceSonicProtection` 
open slack, no more crashing.......

**Comment by krazyito65** [comment]
I ran it again with 0 flags and it still works fine as normal.

**Comment by nlowe** [comment]
Once slack starts once without the readonly protection it shouldn't crash again, even if you add `-ForceSonicProtection`. Tl;Dr if you stopped crashing this change won't have any affect except hopefully prevent crashes in the future should they change something.

**Comment by sheldonhull** [comment]
I'm on `4.0.2` after uninstalling and reinstalling with MSI version from chocolatey on windows. I had to run with `ForceSonicProtection` for it to stop looping. However, this didn't seem to load with the dark theme when it ran. I reran without the flag the second time and it worked then. I had to remove the previous appdata folder to prevent errors in the if logic too. Pretty sure the logic had issues with the fact I had an empty slack folder in the local appdata. 

This resolved my issues and allowed it to load.
```powershell

# .\slack-dark-mode.ps1 -ForceSonicProtection i did this first, but think the main issue was empty appdata folder
Remove-Item "$ENV:LocalAppData\slack"
.\slack-dark-mode.ps1

```

**Comment by krazyito65** [comment]
uhh... removing local app data would kill your entire install, wouldn't it??
