### ISSUE TITLE
Channels list scroll bar poorly themed

### ISSUE THREAD

**Issue by robmonte** [LanikSJ/slack-dark-mode#224]
**Describe the bug**
The channel list scroll bar is extremely difficult to see as it is black on black.
Edit: The issue expanded in the comments as it affects more than just the channels list scroll bar. Most aren't themed properly - https://github.com/LanikSJ/slack-dark-mode/issues/224#issuecomment-528972265

**To Reproduce**
1\. Go to 'Browse Channels'
2\. See error

**Expected behavior**
The scroll bar should be use the lighter gray color to contrast with the background for better visibility

**Screenshots**
![image](https://user-images.githubusercontent.com/17119716/64290222-4c2be800-cf2b-11e9-8ef5-8d929af3ee5a.png)

**Desktop (please complete the following information):**

-   OS: macOS
-   Slack Version: 4.1.0

**Additional context**
N/A

**Comment by LanikSJ** [comment]
@robmonte can you double check this for me now? Should be fixed already.

**Comment by dhruvasagar** [comment]
@LanikSJ My PR only fixed the list styles, not the scrollbar. The scrollbar issue still persists from what I can tell.

**Comment by robmonte** [comment]
Copying my comment from the other issue posted

-----

It seems like most of the scroll bars are off, with the exception of the main left sidebar's scroll bar. The main sidebar looks good, currently like this:
![image](https://user-images.githubusercontent.com/17119716/64357927-281fe380-cfcb-11e9-9411-58e2635b441d.png)   <---------- This one looks good and they all should look like this

Inside an actual channel, the scrollbar is a different color:
![image](https://user-images.githubusercontent.com/17119716/64357999-44238500-cfcb-11e9-9a25-15a445babc70.png)

When reading a thread, it looks more like the channel list scrollbar in the separate issue I opened:
![image](https://user-images.githubusercontent.com/17119716/64358135-7cc35e80-cfcb-11e9-8ed5-1f2ac523cfd5.png)

**Comment by LanikSJ** [comment]
Yeah I'm still seeing it also in channels list?  There's also #242 which has wrong scrollbars.

**Comment by Brejendra-Amex** [comment]
With the latest update Version 4.0.3 (App Store) . I’m not able to make it dark again. Any advise ?
